baseURL = "http://devstage.vercel.app"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "mainroad"

[Author]
  name = "John Doe"
  bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "img/avatar.png"

[Params]
  description = "John Doe's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  toc = true
  authorbox = true
  pager = true
  post_meta = ["author", "date", "categories"] # Order of post meta information
  mainSections = ["post", "blog", "news"]
  
[Params.logo]
  subtitle = "Just another site" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
  
[menu]
 
 [[menu.main]]
    identifier = "About"
    name = "About"
    title = "about"
    url = "/about/"
    weight = 10
 
 [[menu.main]]
    identifier = "news"
    name = "news"
    title = "news"
    url = "/news/"
    weight = 20
  [[menu.main]]
    identifier = "top lists"
    name = "top lists"
    title = "top lists"
    url = "/top-lists/"
    weight = 30
  [[menu.main]]
    identifier = "comparison"
    name = "comparison"
    title = "comparison"
    url = "/comparison/"
    weight = 40
  [[menu.main]]
    identifier = "app deals"
    name = "app deals"
    title = "app deals"
    url = "/app-deals/"
    weight = 50
  [[menu.main]]
    identifier = "contact us"
    name = "contact us"
    title = "contact us"
    url = "/contact-us/"
    weight = 60
